# -*- coding: utf-8 -*-
"""Sphinx configuration for the pymacos documentation.

Pages are written in Markdown (MyST) and rendered with the Read the Docs theme.
The API reference is generated by autodoc: the package imports on any OS, so it
builds on Read the Docs' Linux machines too.
"""

import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.abspath(".."))

# -- Project information -----------------------------------------------------

project = "pymacos"
author = "Jean Loui Bernard Silva de Jesus"
copyright = f"{datetime.now().year}, {author}"

from macos import __version__ as release  # noqa: E402

version = ".".join(release.split(".")[:2])

# -- General configuration ---------------------------------------------------

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinx_copybutton",
    "sphinxext.opengraph",
]

source_suffix = {
    ".md": "markdown",
    ".rst": "restructuredtext",
}

master_doc = "index"
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

# -- HTML output -------------------------------------------------------------

html_theme = "sphinx_rtd_theme"
html_title = "pymacos"

html_theme_options = {
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 3,
    "prev_next_buttons_location": "bottom",
    "style_external_links": True,
}

# "Edit on GitHub" link, plus the data the sidebar "Star on GitHub" CTA reads.
html_context = {
    "display_github": True,
    "github_user": "JeanExtreme002",
    "github_repo": "pymacos",
    "github_version": "main",
    "conf_py_path": "/docs/",
}

html_static_path = ["_static"]
html_css_files = ["custom.css"]

# -- Extensions --------------------------------------------------------------

# Link previews (Open Graph and Twitter cards): a page shared on social networks
# or chat apps shows its title, its first paragraph and the project's card, the
# same image as the GitHub repository's social preview.
ogp_site_url = "https://macos.readthedocs.io/en/latest/"
ogp_site_name = "pymacos"
ogp_image = "_static/brand/social-preview.png"
ogp_image_alt = "pymacos: Control your Mac from Python"
ogp_social_cards = {"enable": False}  # one card for every page, not one drawn per page
ogp_custom_meta_tags = ['<meta name="twitter:card" content="summary_large_image">']

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
}

autodoc_default_options = {
    "members": True,
    "show-inheritance": True,
}
autodoc_member_order = "bysource"
autodoc_typehints = "description"
# The type variable that keeps a decorated function's signature: internal, not documented.
nitpick_ignore = [("py:class", "macos.auth._Function")]

copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True
